
# issue #152 (b): local connections were not receiving
# ansible_python_interpreter treatment, breaking virtualenvs.

# To test:
#   - Ensure system Python does not have boto3 installed.
#   - Run /path/to/venv/ansible-playbook ... with the virtualenv deactivated.
#     Observe success.
#   - Run ansible-playbook ... with the virtualenv activated. Observe success.

- hosts: all
  gather_facts: false
  tasks:

  - local_action: cloudformation_facts
